// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfxzDROw-Vl1FaeuggrcgC72cgYSyR_vU',
    appId: '1:160183454280:web:670b6765a71240d085e67d',
    messagingSenderId: '160183454280',
    projectId: 'flutter-vlu',
    authDomain: 'flutter-vlu.firebaseapp.com',
    storageBucket: 'flutter-vlu.appspot.com',
    measurementId: 'G-V5Z1XBHYSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_0N1FwjC6Mn2VD6sIqLyeSk3Mad1Xss',
    appId: '1:160183454280:android:7ce9aacf7208b3f185e67d',
    messagingSenderId: '160183454280',
    projectId: 'flutter-vlu',
    storageBucket: 'flutter-vlu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zzobwDmMcN2FiM933jfr5PyOKr-pd1Q',
    appId: '1:160183454280:ios:a0bb64efd160a11d85e67d',
    messagingSenderId: '160183454280',
    projectId: 'flutter-vlu',
    storageBucket: 'flutter-vlu.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1zzobwDmMcN2FiM933jfr5PyOKr-pd1Q',
    appId: '1:160183454280:ios:5f9a6c15c4b1ec0585e67d',
    messagingSenderId: '160183454280',
    projectId: 'flutter-vlu',
    storageBucket: 'flutter-vlu.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
